### ISSUE TITLE
Display image on mapped handler for interactive animation

### ISSUE THREAD

**Issue by ysig** [attwad/python-osc#125] opened 2020-10-28 20:31 UTC
I have a huge problem using your package for any sort of animation from matplotlib to opencv.
As an example I post the following code:

```
import numpy as np
from pythonosc import dispatcher
from pythonosc import osc_server
import cv2

ip = "127.0.0.1"
port = 12000

def show_frame(*args):
    print(args)
    npimage = np.random.standard_normal([512, 512, 3])
    # specified font size 
    cv2.imshow('frame', npimage)

dispatcher = dispatcher.Dispatcher()
server = osc_server.BlockingOSCUDPServer((ip, port), dispatcher)
dispatcher.map("/wek/outputs", show_frame)
server.serve_forever()
```

**Comment by attwad** [comment] 2020-10-29 13:49
You're not explaining what your problem is but I suppose the problem is frame-rate related?

You're using a blocking server, I suggest switching to something asynchronous instead.
https://python-osc.readthedocs.io/en/latest/server.html

**Comment by ysig** [comment] 2020-10-29 15:25
Hey Timothe,

My problem is that I cannot understand how to use your package so each time I receive a new signal I update an image on the screen. My problem is not frame-rate related, it has to do with the fact that I get nothing as an output. The callback function seems https://python-osc.readthedocs.io/en/latest/server.html isolated in this example and I cannot understand how to use it for my scope.

**Comment by ysig** [comment] 2020-10-29 17:23
I managed to do it with a redering function and global variables.

```
from pythonosc.osc_server import AsyncIOOSCUDPServer
from pythonosc.dispatcher import Dispatcher
import asyncio
import matplotlib.pyplot as plt
import matplotlib.cbook
import warnings
import numpy as np


ip = "127.0.0.1"
port = 12000

current_image = np.random.standard_normal([512, 512, 3]).astype(dtype=np.uint8)
def show_frame(*args):
    global current_image
    print('new_image')
    npimage = np.random.standard_normal([512, 512, 3]).astype(dtype=np.uint8)
    # specified font size 
    current_image = npimage

dispatcher = Dispatcher()
dispatcher.map("/wek/outputs", show_frame)
server = AsyncIOOSCUDPServer((ip, port), dispatcher, asyncio.get_event_loop())

async def loop():
    """Example main loop that only runs for 10 iterations before finishing"""
    plt.ion()
    fig1, ax1 = plt.subplots()
    ax1.axis('off')
    axim1 = plt.imshow(np.zeros((512,512, 3)))
    i = 0
    global current_image
    while True:
        print("plot = " + str(i))
        axim1.set_data(current_image)
        current_image = current_image*0.9
        fig1.canvas.flush_events()
        i += 1
        await asyncio.sleep(0.1)

async def init_main():
    server = AsyncIOOSCUDPServer((ip, port), dispatcher, asyncio.get_event_loop())
    transport, protocol = await server.create_serve_endpoint()  # Create datagram endpoint and start serving

    await loop()  # Enter main loop of program
    transport.close()  # Clean up serve endpoint

if __name__ == '__main__':
    asyncio.run(init_main())
```
If you have a better way in mind, let me know!
Thanks for this package and for your support.

**Comment by attwad** [comment] 2020-11-01 16:20
Great, if you want to avoid global vars (you should) you can move `show_frame()` and `loop()` into a class which holds the `current_image`.
I'm closing this considering you've figured it out, cheers.

**Closed by attwad** 2020-11-01 16:20 UTC

**Comment by ysig** [comment] 2020-11-01 20:29
Can you write a sketch of what you propose, because it's not obvious for e how to do this?
I haven't found anything relevant to your documentation, so this could stand as a nice example.
how do I map the dispatcher to the function of an intialized objects?

Would something like this work:

`dispatcher.map("/wek/outputs", object.show_frame)`

**Comment by attwad** [comment] 2020-11-02 10:05
Something roughly like below:
(btw you had defined AsyncIOOSCUDPServer twice in your script above, that's bound to create issues)
There's nothing in the docs because that's not specific to how this library works, it's just how one can make use of python classes to encapsulate stuff instead of exposing global variables, hope that helps.

```
class ImageDisplay:
  def __init__(self):
    self.current_image = np.random.standard_normal([512, 512, 3]).astype(dtype=np.uint8)

  def show_frame(*args):
    npimage = np.random.standard_normal([512, 512, 3]).astype(dtype=np.uint8)
    self.current_image = npimage

    async def loop():
      plt.ion()
      fig1, ax1 = plt.subplots()
      ax1.axis('off')
      axim1 = plt.imshow(np.zeros((512,512, 3)))
      i = 0
      while True:
        print("plot = " + str(i))
        axim1.set_data(self.current_image)
        self.current_image = self.current_image*0.9
        fig1.canvas.flush_events()
        i += 1
        await asyncio.sleep(0.1) 

async def init_main():
    server = AsyncIOOSCUDPServer((ip, port), dispatcher, asyncio.get_event_loop())
    transport, protocol = await server.create_serve_endpoint()  # Create datagram endpoint and start serving

    await loop()  # Enter main loop of program
    transport.close()  # Clean up serve endpoint

if __name__=="__main__":
  dispatcher = Dispatcher()
  display = ImageDisplay()
  dispatcher.map("/wek/outputs", display.show_frame)
  server = AsyncIOOSCUDPServer((ip, port), dispatcher, asyncio.get_event_loop())
  asyncio.run(init_main())
```

**Comment by ysig** [comment] 2020-11-02 11:07
Ok thanks!

Στις Δευ, 2 Νοε 2020 στις 12:05 μ.μ., ο/η Timothé <notifications@github.com>
έγραψε:
